### ISSUE TITLE
clean up "mpas15-3" grid entries

### ISSUE THREAD

**Issue by adamrher** [ESMCI/ccs_config_cesm#153]
@slevis-lmwg notes:

> When I type git grep mpasa15-3 in /ccs_config, I get:
>
>```component_grids_mct.xml:  <domain name="mpasa15-3conus">
>component_grids_nuopc.xml:  <domain name="mpasa15-3conus">
>component_grids_nuopc.xml:    <mesh driver="nuopc">$DIN_LOC_ROOT/share/meshes/mpasa15-3.conus_ESMF_desc.210816.nc</mesh>
>modelgrid_aliases_mct.xml:  <model_grid alias="mpasa15-3_mpasa15-3" not_compset="_POP">
>modelgrid_aliases_mct.xml:    <grid name="atm">mpasa15-3</grid>
>modelgrid_aliases_mct.xml:    <grid name="lnd">mpasa15-3</grid>
>modelgrid_aliases_mct.xml:    <grid name="ocnice">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:  <model_grid alias="mpasa15-3_mpasa15-3" not_compset="_POP">
>modelgrid_aliases_nuopc.xml:    <grid name="atm">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:    <grid name="lnd">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:    <grid name="ocnice">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:  <model_grid alias="mpasa15-3-conus_mpasa15-3-conus" not_compset="_POP">
>modelgrid_aliases_nuopc.xml:    <grid name="atm">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:    <grid name="lnd">mpasa15-3</grid>
>modelgrid_aliases_nuopc.xml:    <grid name="ocnice">mpasa15-3</grid>```

>In my copy of component_grids_nuopc.xml I removed "conus" from the name to get things to work. If we prefer a different fix, I'm open to that.

I responded

> Ah, I see. So the problem is that the grid aliases are referencing "mpasa15-3" but it doesn't actually exist in component_grids_nuopc.xml. So we need to clean up moodelgrid_aliases_xxx to only reference "mpasa15-3conus". And it looks like a duplicate grid alias in nuopc.

This ```mpasa15-3conus``` grid is not installed in any other externals. I checked with Bill Skamarock and he said the origins of this partial grid install occurred during a time when we were more aspirational in getting these big grids running in CESM. This grid is not runnable at present, but maybe it might be in the future so I'd just recommend fixing the inconsistencies and not removing ```mpasa15-3conus``` altogether.

@PeterHjortLauritzen @ekluzek

**Comment by ekluzek** [comment]
Wait @adamrher I'm not clear what you are suggesting. Sam's suggestion was to change mpas15-3conus to mpas15-3. I think the way to go is to change mpas15-3 to mpas15-3conus. Either way should work, but it has impact on how models will refer to the grid. I'm thinking we need to do the later so only mpas15-3conus is used. Do you agree with that?

**Comment by adamrher** [comment]
Yes, I agree. I guess I wasn't clear on that point.

**Comment by ekluzek** [comment]
The other thing I should have asked is who is going to do this? I'm assuming you will. And once it's done you'll let us know we'll integrate into both CAM and CTSM. Does that sound right?

**Comment by adamrher** [comment]
Yeah I can do a PR that fixes this and https://github.com/ESMCI/ccs_config_cesm/issues/152.

What is to "integrate into both CAM and CTSM" ? We are not supporting this grid in CESM3.0, and neither mpasa15-3 nor mpasa15-3conus are referenced anywhere in CAM. Are they referenced in CTSM anywhere?

**Comment by ekluzek** [comment]
Oh, I was going to say it's in the Grids file. But, now I notice it has a question mark...

mpasa15-3conus?

So this is just something that needs to happen post CESM3. That helps to know. Thanks...

**Comment by adamrher** [comment]
Yep. There is no X in the "Install in CESM3" column for 15-3conus grid.

But there is a X? for uniform 15 km ... that's my next task to figure out.
