### ISSUE TITLE
Drop nvhpc to 23.7 on derecho?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/ccs_config_cesm#187]
MOM6 has some stand-alone tests that run fine on derecho when built with nvhpc 24.3 until we turn MARBL on -- with the MARBL tracers enabled, the runs abort with a very unphysical state. Building the model with 23.7 instead of 24.3 lets those tests with the MARBL tracers run successfully. I haven't tested this, but I suspect there will be issues running MARBL in the global CESM if it is built with 24.3, so I was hoping we could drop back to an older compiler version until someone (probably me) has a chance to track down what is causing the issue with the newer compiler.

**Comment by jedwards4b** [comment]
Not going backward - since nvhpc is not the default compiler I think that we should just note this as a known failure and report to nvidia.

**Comment by mnlevy1981** [comment]
Fair enough -- once beta04 is ready, I'll do some testing with nvhpc and try to come up with a useful report for nvidia. Thanks!

**Comment by sjsprecious** [comment]
@mnlevy1981 the latest nvidia compiler version on Derecho is `nvhpc/24.9`, does it work for your MARBL build?

**Comment by jedwards4b** [comment]
I'll be working on an update of compilers on derecho next week.
