### ISSUE TITLE
Old mpt and netcdf-mpi versions on Cheyenne

### ISSUE THREAD

**Issue by sjsprecious** [ESMCI/ccs_config_cesm#43]
Cheyenne has recently updated the default library version including `mpt/2.25` and `netcdf-mpi/4.8.1`. Is there a reason that these versions are not updated in the `config_machines.xml` file accordingly?

**Comment by jedwards4b** [comment]
Compiler updates often change answers and so must be done carefully.  But we can update mpt and netcdf-mpi (and pnetcdf too) at will.

**Comment by sjsprecious** [comment]
Thanks @jedwards4b.
