### ISSUE TITLE
add ne3pg3 grid and ne3pg3_ne3pg3_mg37 grid alias

### ISSUE THREAD

**Issue by adamrher** [ESMCI/ccs_config_cesm#76]
This is the ccs_config issue associated with installing the ne3pg3 grid into CESM. This is the corresponding CAM issue: https://github.com/ESCOMP/CAM/issues/726 and this is the corresponding CTSM issue: 
 https://github.com/ESCOMP/CTSM/issues/1927.

This issue needs to be addressed first, and then the the CAM and CTSM issues can be addressed.

Here are the code mods needed for modelgrid_aliases_nuopc.xml:

```
  <model_grid alias="ne3pg3_ne3pg3_mg37" not_compset="_POP">
    <grid name="atm">ne3np4.pg3</grid>
    <grid name="lnd">ne3np4.pg3</grid>
    <grid name="ocnice">ne3np4.pg3</grid>
    <mask>gx3v7</mask>
  </model_grid>
```

And here's the entry for component_grids_nuopc.xml:

```
  <domain name="ne3np4.pg3">
    <nx>486</nx> <ny>1</ny>
    <mesh>/glade/work/aherring/grids/uniform-res/ne3np4.pg3/grids/ne3pg3_ESMFmesh_c221214_cdf5.nc</mesh>
    <desc>ne3np4 is Spectral Elem 10-deg grid with a 3x3 FVM physics grid:</desc>
    <support>EXPERIMENTAL FVM physics grid</support>
  </domain>
```

**Comment by fischer-ncar** [comment]
Closed by #85
