### ISSUE TITLE
remove _CLM from "not_compset" for ne16pg3_ne16pg3_mg17 alias

### ISSUE THREAD

**Issue by adamrher** [ESMCI/ccs_config_cesm#90]
remove _CLM from" not_compset" for ne16pg3_ne16pg3_mg17 alias in modelgrid_aliases_nuopc.xml. This is to permit functional support for the 2deg spectral-element CSLAM in F-cases, which is being introduced in CTSM: https://github.com/ESCOMP/CTSM/pull/1973.

**Comment by ekluzek** [comment]
This was completed in #92
